server {
      listen 80;
      server_name localhost;
      # Redirect HTTP to HTTPS
      return 301 https://$host$request_uri;
}

server {
      listen 443 ssl;
      server_name localhost;

      # SSL Certificate Configuration
      ssl_certificate /etc/ssl/certs/server.crt;
      ssl_certificate_key /etc/ssl/certs/server.key;

      # SSL Security Settings
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_prefer_server_ciphers on;
      ssl_ciphers HIGH:!aNULL:!MD5;

      root /usr/share/nginx/html/views;
      index index.html;

      location / {
          try_files $uri $uri.html $uri/ /index.html;
      }

      location /public {
          alias /usr/share/nginx/html/public;
          try_files $uri =404;
      }
}